### ISSUE TITLE
SetMouseScreenAbsolutePosition bug

### ISSUE THREAD

**Issue by nazarpunk** [UnryzeC/UjAPI#11]
```c++
void main() {
    TimerStart(CreateTimer(), 1.f, true, function() {
        SetMouseScreenAbsolutePosition(.5f, .5f);
        print(GetMouseScreenAbsoluteX() + " | " + GetMouseScreenAbsoluteY()+ "\n");
    });
}
```

## Expected result

Cursor at center, console print `0.5 | 0.5`.

## Actual result

Cursor at left top, console print `0 | 1`.

![image](https://github.com/user-attachments/assets/5df3e3a5-d937-48c1-946c-3e5a08f36d5c)

**Comment by UnryzeC** [comment]
Will be fixed in upcoming version.

Changelog: https://github.com/UnryzeC/UjAPI/blob/main/uJAPIFiles/Changelogs/UjAPI%20v1.1.25.277.txt
