### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by N1ghtSiren** [UnryzeC/UjAPI#2]
1.  `SetAbilityIntegerLevelField(a, ABILITY_ILF_TARGET_TYPE, 0, 1)`
-> not updates ingame, uses base option from object data
ability based on channel "ANcl"

2. `BlzSetAbilityTooltip(abilityid, "name", 0)`
-> critical error
any ability (tested on "AHbz", "A000")
```
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:02A58069
The instruction at '0x02A58069' referenced memory at '0xA2EC42E0'.
```

3. ? manipulations with ability data 
-> critical error on exit
may be related to (1)
can investigate further if needed
```
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:027EEA87
The instruction at '0x027EEA87' referenced memory at '0x1A0F00BC'.
```

**Comment by UnryzeC** [comment]
Should be fixed in v1.0.19.78, thanks.
