### ISSUE TITLE
Click Event for Item Button Prevents Normal Inventory Functions

### ISSUE THREAD

**Issue by SinisterLuffy** [UnryzeC/UjAPI#6]
When FRAME_CONTROL_CLICK is registered for ORIGIN_FRAME_ITEM_BUTTON, the item on the button cannot be swapped with another item, moved to another slot, or used. It can be dropped, however.

![Test Inventory](https://github.com/UnryzeC/UjAPI/assets/129889822/85415306-1c28-4d52-8e15-7e66782ae89f)

**Comment by UnryzeC** [comment]
While I do know of this issue, sadly I did not find a way to fix it, at least not yet. If I won't find a way today, I will just skip this for the future versions, as I am planning on releasing update tomorrow.

Thanks for the report.

**Comment by SinisterK** [comment]
In case you don't find a way to solve this issue, can we gain access to the frame that is on the cursor frame when an item is held? That frame's texture can then be checked against each item button's icon to determine which item button was clicked.

**Comment by UnryzeC** [comment]
There is no frame, it’s just a texture sadly. All it contains is the order, aka which slot to switch with witch and that’s about it.

**Comment by UnryzeC** [comment]
Anyhow, as a temporary measure (if I will ever find a way to fix this issue) is to save Item Slot Id whenever a Click with Right Mouse Button was issued, then you can check which frame was clicked with Left Mouse Button and get its Id (or even better save it in hashtable) and do the item switch manually.

Another way would be to NOT register click event for Item buttons, if you don't really use code for it.

**Comment by UnryzeC** [comment]
Closing, as I couldn't find a way to solve the issue, I am still keeping it in mind, but priority is lowest possible.

**Comment by UnryzeC** [comment]
Update, this issue was actually fixed (not sure when and how), probably when I fully rewrote NetCode parser, aka I fully handle it myself, so game's outdated NetCode parser is not used anymore/
