### ISSUE TITLE
Setting orientation has no effect on SPRITE frames

### ISSUE THREAD

**Issue by SinisterK** [UnryzeC/UjAPI#7]
I attempted to call SetFrameSpriteOrientation or its Ex equivalent on my custom SPRITE frame, but the sprite's orientation remained unchanged in game. I even tried the individual functions and even the recently added functions for working directly with sprites. Nothing worked.

**Comment by UnryzeC** [comment]
Working usage of it here: https://xgm.guru/p/ujapi/UjAPI-Hero-Pick-System

It's possible that current version has issues, test on upcoming build show no issues.
