### ISSUE TITLE
Switch Maps in Multiplayer

### ISSUE THREAD

**Issue by SinisterLuffy5** [UnryzeC/UjAPI#8]
Like how you can switch maps in a campaign, give the ability to switch maps in multiplayer.  Perhaps, make the following function actually do something in multiplayer?

`ChangeLevel(mapfile, screenScreenOn)`

**Comment by UnryzeC** [comment]
Not really feasible or possible without ensuring somehow that all players have the same map and then somehow re-host game and force all players in that lobby. Also, why? X_X

**Comment by SinisterLuffy5** [comment]
I was thinking more along these lines: A player has their unit enter a designated area -> Download map -> Send player straight to the loading screen of the downloaded map. So, a single player, not everyone, will be moved to the new map. 

All for creating your own MMORPG lol, albeit on a smaller scale.
