### ISSUE TITLE
EXExecuteScript crashing the game without error popup

### ISSUE THREAD

**Issue by SinisterLuffy5** [UnryzeC/UjAPI#9]
After the changes made to EXExecuteScript on v1.1.16.224, this function has been producing constant crashes on a map that I am developing.  Where as on v1.1.16.222, I did not experience any crash from using this function.
Map link: https://drive.google.com/file/d/1RITTtKOusD8WgsaH7l2qLlfUKG04Ue-Y/view?usp=drive_link

**Comment by UnryzeC** [comment]
I suggest NOT using this native at all, all of the things it does are available via Field API, I will take a look again, but it's under lowest/non-existent priority as it's just a bad API to begin with.

**Comment by UnryzeC** [comment]
Anyhow, small fixes were applied to it, so it should no longer crash at least. This fix will be available in the upcoming version.
